USE ScriptCoordinationDB;

ALTER TABLE DanhSachNhac
    ADD COLUMN IF NOT EXISTS TenFileGoc VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS LoaiFile VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS NoiDungFile LONGBLOB NULL;

ALTER TABLE DanhSachNhac
    MODIFY COLUMN NoiDungFile LONGBLOB NULL;

